export type CreditSalesManagerCreditSalesDictionary = {
  title: string;
  subtitle: string;
  newBtn: string;
  kpiTotalPending: string;
  kpiOverdue: string;
  kpiLoanItems: string;
  kpiThisMonth: string;
  filterAll: string;
  filterCredit: string;
  filterLoan: string;
  filterStatusAll: string;
  tableDocNo: string;
  tableCustomer: string;
  tableType: string;
  tableAmountQty: string;
  tablePaidProgress: string;
  tableRemaining: string;
  tableDueDate: string;
  tableStatus: string;
  tableActions: string;
  viewBtn: string;
  statusPending: string;
  statusPartial: string;
  statusCompleted: string;
  statusOverdue: string;
  statusCancelled: string;
  typeCredit: string;
  typeLoan: string;
  createTitle: string;
  tabCredit: string;
  tabLoan: string;
  customerLabel: string;
  customerRequired: string;
  customerPlaceholder: string;
  dueDateLabel: string;
  dueDateRequired: string;
  productsLabel: string;
  addProductBtn: string;
  productNamePlaceholder: string;
  searchPlaceholder: string;
  scanWithCamera: string;
  skuLabel: string;
  stockLabel: string;
  priceLabel: string;
  unitLabel: string;
  noProductsFound: string;
  createSubtitle: string;
  creditDesc: string;
  loanDesc: string;
  dueDateOptional: string;
  noItemsYet: string;
  noItemsHint: string;
  pricePlaceholder: string;
  qtyPlaceholder: string;
  colName: string;
  colPrice: string;
  colQty: string;
  colTotal: string;
  noteLabel: string;
  notePlaceholder: string;
  summaryQtyLabel: string;
  summaryAmountLabel: string;
  pieces: string;
  cancelBtn: string;
  saveBtn: string;
  saving: string;
  noItemsError: string;
  noCustomerError: string;
  detailCustomerLabel: string;
  detailCreatedByLabel: string;
  detailCreatedAtLabel: string;
  detailDueDateLabel: string;
  detailTotalLabel: string;
  detailPaidLabel: string;
  detailRemainingLabel: string;
  detailItemsTitle: string;
  detailPayHistoryTitle: string;
  detailNoPayments: string;
  closeBtn: string;
  printBillBtn: string;
  cancelSaleBtn: string;
  receivePaymentBtn: string;
  returnGoodsBtn: string;
  returnTitle: string;
  returnSubtitle: string;
  returnColReturnable: string;
  returnColReturnQty: string;
  returnSubmitBtn: string;
  returnSaving: string;
  returnSuccess: string;
  returnNothingError: string;
  paymentMethodReturn: string;
  cancelConfirm: string;
  paymentTitle: string;
  paymentOutstandingLabel: string;
  paymentAmountLabel: string;
  paymentMethodLabel: string;
  paymentMethodCash: string;
  paymentMethodTransfer: string;
  paymentNoteLabel: string;
  paymentNotePlaceholder: string;
  paymentConfirmBtn: string;
  paymentExactBtn: string;
  paymentAmountError: string;
  empty: string;
  emptyHint: string;
  loading: string;
  createdSuccess: string;
  paymentSuccess: string;
  cancelSuccess: string;
  cancelFailed: string;
  noCustomersFound: string;
  stockExceeded: string;
  summaryItemsLabel: string;
  itemsUnit: string;
  colRemove: string;
  errInsufficientStock: string;
  errProductInactive: string;
  errInvalidItem: string;
  errProductNotFound: string;
  errOverpayment: string;
  errSaveFailed: string;
  errDiscountCap: string;
  colDiscount: string;
  discountUnitAmount: string;
  discountUnitPercent: string;
  billDiscountLabel: string;
  billDiscountPlaceholder: string;
  vatSectionTitle: string;
  vatToggleLabel: string;
  vatRateLabel: string;
  vatIncludedLabel: string;
  vatExclusiveLabel: string;
  sumSubtotal: string;
  sumLineDiscount: string;
  sumLevelDiscount: string;
  sumBillDiscount: string;
  sumAfterDiscount: string;
  sumVat: string;
  sumGrandTotal: string;
  listSearchPlaceholder: string;
  filterDateFrom: string;
  filterDateTo: string;
  filterClear: string;
  rowCancelTitle: string;
  dashTitle: string;
  dashTotalValue: string;
  dashCollected: string;
  dashCollectionRate: string;
  dashThisMonthValue: string;
};

export type CreditSalesManagerBillModalDictionary = {
  title: string;
  print: string;
  close: string;
  loading: string;
  notFound: string;
};

export type CreditSalesManagerCreditSalesManagerProps = {
  dictionary: CreditSalesManagerCreditSalesDictionary;
  billDictionary: CreditSalesManagerBillModalDictionary;
  locale: string;
  prefilledCustomerId?: string;
  prefilledCustomerName?: string;
};

export type CreditSalesManagerDraftItem = {
  id: string;
  product_id: string;
  product_name: string;
  unit?: string;
  price: number;
  quantity: number;
  discountType: "amount" | "percent";
  discountValue: number;
};

export type CreditStatementModalBillModalDict = {
  title: string;
  print: string;
  close: string;
  loading: string;
  notFound: string;
};

export type CreditStatementModalProps = {
  creditSaleId: string;
  open: boolean;
  onClose: () => void;
  dict: CreditStatementModalBillModalDict;
};

export type CustomerComboboxCustomerComboboxLabels = {
  placeholder: string;
  noResults: string;
};

export type ProductComboboxProductPick = {
  product_id: string;
  product_name: string;
  unit?: string;
  price: number;
  quantity: number;
  total: number;
};

export type ProductComboboxProductComboboxLabels = {
  searchPlaceholder: string;
  skuLabel: string;
  stockLabel: string;
  noProductsFound: string;
  stockExceeded: string; // uses {count} — shown when stock is 0 or already maxed in the cart
  scanWithCamera?: string;
};
