// Explicit dictionary shapes for the Inventory + Stock-Count modules.
// These structurally match locales/{th,en}.json `inventory` and `count` sections
// (Dictionary = typeof th), so the server pages can pass dictionary.inventory /
// dictionary.count directly.

export type InventoryAdjustDictionary = {
  title: string;
  typeReceive: string;
  typeDecrease: string;
  typeSet: string;
  quantity: string;
  reason: string;
  reasonPlaceholder: string;
  reasonRequired: string;
  reference: string;
  referencePlaceholder: string;
  currentStock: string;
  newStock: string;
  difference: string;
  preview: string;
  confirm: string;
  back: string;
  save: string;
  saving: string;
  cancel: string;
  invalidNegative: string;
  success: string;
  error: string;
  location: string;
  targetLocation: string;
  useDefaultLocation: string;
  noDefaultLocation: string;
  selectReason: string;
  note: string;
  notePlaceholder: string;
  noteRequired: string;
  reasonLabels: Record<string, string>;
  // Location-aware adjustment (unified Warehouse + Inventory entry points).
  storeTotal: string;
  locationQty: string;
  selectedLocationLabel: string;
  changeLocation: string;
  selectLocationPrompt: string;
  selectLocationRequired: string;
  noValidLocation: string;
  loadingLocations: string;
  systemQty: string;
  countedQty: string;
  variance: string;
  staleNotice: string;
  highVarianceWarning: string;
  varianceConfirm: string;
  salePointTag: string;
  storageTag: string;
  defaultTag: string;
  useContinuously: string;
  lockedHint: string;
  configureLocationCta: string;
};

export type InventoryDictionary = {
  title: string;
  subtitle: string;
  search: string;
  scanWithCamera: string;
  empty: string;
  loading: string;
  openCount: string;
  kpi: {
    totalSku: string;
    availableUnits: string;
    stockValue: string;
    lowStock: string;
    outOfStock: string;
  };
  salePointHint: string;
  col: {
    product: string;
    available: string;
    salePoint: string;
    storage: string;
    total: string;
    minStock: string;
    status: string;
    stockValue: string;
    actions: string;
  };
  status: { ready: string; low: string; out: string; inactive: string };
  filter: { all: string; ready: string; low: string; out: string };
  noMovement: string;
  action: { adjust: string; history: string; viewProduct: string; more: string };
  countMenu: { start: string; history: string };
  activity: {
    title: string;
    subtitle: string;
    empty: string;
    types: {
      receive: string;
      sale: string;
      adjust: string;
      transfer: string;
      countCorrection: string;
      return: string;
    };
  };
  adjust: InventoryAdjustDictionary;
};

export type CountDictionary = {
  title: string;
  subtitle: string;
  back: string;
  newSession: string;
  noSessions: string;
  sessionList: string;
  items: string;
  wizard: { setup: string; selectItems: string; counting: string; review: string; stepOf: string };
  create: {
    title: string;
    name: string;
    namePlaceholder: string;
    warehouse: string;
    allWarehouses: string;
    location: string;
    selectLocation: string;
    locationHelp: string;
    salePoint: string;
    zone: string;
    zonePlaceholder: string;
    allZones: string;
    category: string;
    allCategories: string;
    staff: string;
    staffPlaceholder: string;
    note: string;
    cancel: string;
    continueToItems: string;
    countType: string;
    countTypeOptions: {
      full: string;
      zone: string;
      category: string;
      cycle: string;
    };
    cycleRule: string;
    cycleRulePlaceholder: string;
    blindCount: string;
    blindCountHelp: string;
    searchCountType: string;
    noCountTypeMatch: string;
    searchWarehouse: string;
    noWarehouseMatch: string;
    searchCategory: string;
    noCategoryMatch: string;
    searchLocation: string;
    noLocationMatch: string;
  };
  preview: {
    title: string;
    warehouse: string;
    zone: string;
    category: string;
    products: string;
    mode: string;
    modeFull: string;
    modePartial: string;
    estimateUnit: string;
    type: string;
    blindCount: string;
    cycleRule: string;
    enabled: string;
    disabled: string;
  };
  select: {
    title: string;
    subtitle: string;
    searchPlaceholder: string;
    selectAll: string;
    clear: string;
    selectedItems: string;
    startCounting: string;
    unassigned: string;
    noProducts: string;
    back: string;
    statusReady: string;
    statusLow: string;
    statusOut: string;
    statusUnassigned: string;
    allStockStatuses: string;
  };
  status: { draft: string; counting: string; review: string; completed: string; cancelled: string };
  col: {
    product: string;
    sku: string;
    barcode: string;
    systemQty: string;
    countedQty: string;
    variance: string;
    status: string;
    note: string;
    location: string;
    currentStock: string;
  };
  variance: { match: string; short: string; over: string; notCounted: string; skipped: string };
  summary: {
    totalItems: string;
    counted: string;
    matched: string;
    short: string;
    over: string;
    notCounted: string;
    totalVariance: string;
    skipped: string;
    remaining: string;
    progress: string;
  };
  scanPlaceholder: string;
  scanNotFound: string;
  scanWithCamera: string;
  countMode: { table: string; quick: string };
  counting: { hidden: string };
  countFilter: {
    all: string;
    notCounted: string;
    counted: string;
    variance: string;
  };
  severity: {
    low: string;
    medium: string;
    high: string;
    critical: string;
  };
  quickScan: {
    title: string;
    hint: string;
    barcodeLabel: string;
    barcodePlaceholder: string;
    countedQtyLabel: string;
    notePlaceholder: string;
    save: string;
    skip: string;
    next: string;
    productFound: string;
    ready: string;
    focusHint: string;
    notFound: string;
    lastSaved: string;
    skipped: string;
    recentActivity: string;
    liveSummary: string;
  };
  action: {
    saveDraft: string;
    review: string;
    continue: string;
    apply: string;
    applying: string;
    cancel: string;
    export: string;
    back: string;
    skip: string;
    resume: string;
    actions: string;
  };
  review: {
    title: string;
    subtitle: string;
    noVariance: string;
    applyConfirm: string;
    applied: string;
    applyNote: string;
    applyError: string;
    legacyNoLocation: string;
    correctionResult: string;
    applyCol: string;
    varianceItems: string;
    totalShortage: string;
    totalOverage: string;
    netVariance: string;
    willUpdate: string;
    backToCounting: string;
    reason: string;
    reasonPlaceholder: string;
    otherReasonPlaceholder: string;
    requiredReason: string;
    reasonNotRequired: string;
    reasonOptions: {
      "": string;
      counting_error: string;
      misplaced_product: string;
      damaged_product: string;
      missing_product: string;
      receiving_not_recorded: string;
      sale_not_recorded: string;
      previous_adjustment_error: string;
      other: string;
    };
    itemsIncreased: string;
    itemsDecreased: string;
    qtyIncrease: string;
    qtyDecrease: string;
    netChange: string;
    valueIncrease: string;
    valueDecrease: string;
    netImpact: string;
    inventoryImpact: string;
    costUnavailable: string;
    sessionSummary: string;
    sessionName: string;
    sessionDate: string;
    creator: string;
    completedBy: string;
    completedAt: string;
    warehouse: string;
    category: string;
    sessionStatus: string;
    results: string;
    varianceTable: string;
    adjusted: string;
    adjustedYes: string;
    adjustedNo: string;
    user: string;
    timestamp: string;
    auditTrail: string;
    noAuditTrail: string;
    sessionDetailTitle: string;
    sessionDetailSubtitle: string;
    exportExcel: string;
    exportPdf: string;
    printReport: string;
    pdfOpenError: string;
    showVarianceOnly: string;
    showAllItems: string;
    confirmApply: string;
    itemsToUpdate: string;
    confirmationHelp: string;
    approvalWarning: string;
    severityLabel: string;
  };
  list: {
    session: string;
    warehouse: string;
    zone: string;
    category: string;
    status: string;
    totalItems: string;
    countedItems: string;
    varianceItems: string;
    createdBy: string;
    createdAt: string;
    actions: string;
    continue: string;
    review: string;
    viewResult: string;
    cancel: string;
    delete: string;
    allWarehouses: string;
    allCategories: string;
    allStatuses: string;
    pending: string;
    searchPlaceholder: string;
    noFilteredSessions: string;
    unknownUser: string;
    type: string;
    progress: string;
    lastActivity: string;
    dashboard: {
      totalSessions: string;
      draft: string;
      counting: string;
      review: string;
      completed: string;
      cancelled: string;
    };
  };
  empty: string;
  draftSaved: string;
  cancelConfirm: string;
  cancelSessionConfirm: string;
  deleteSession: string;
  deleteConfirm: string;
};
