import type { Locale } from "@/lib/locale-config";

export type CustomerNetworkManagerCustomerNetworkDictionary = {
  activeLabel: string;
  activeStatus: string;
  addPointsLabel: string;
  addressLabel: string;
  branchLabel: string;
  branchPlaceholder: string;
  cancelEdit: string;
  cancelLabel: string;
  closeLabel: string;
  createSubtitle: string;
  createTitle: string;
  createTitleNew: string;
  discountRuleHint: string;
  discountRuleSubtitle: string;
  deleteConfirm: string;
  deleteLabel: string;
  deletedSuccess: string;
  discountPercentLabel: string;
  discountRuleTitle: string;
  editLabel: string;
  addressPlaceholder: string;
  emailLabel: string;
  emailPlaceholder: string;
  empty: string;
  filterAllLevels: string;
  fullNameLabel: string;
  fullNamePlaceholder: string;
  fullNameRequired: string;
  phonePlaceholder: string;
  inactiveStatus: string;
  invoiceLabel: string;
  kpiGold: string;
  kpiPlatinum: string;
  kpiPoints: string;
  kpiSilver: string;
  kpiTotal: string;
  kpiVip: string;
  levelGeneral: string;
  levelGold: string;
  levelLabel: string;
  levelPlatinum: string;
  levelRequired: string;
  levelSilver: string;
  levelVip: string;
  listTitle: string;
  loading: string;
  memberCodeAuto: string;
  memberCodeHint: string;
  memberCodeLabel: string;
  noteLabel: string;
  phoneLabel: string;
  pointsLabel: string;
  requestFailed: string;
  save: string;
  saveDiscount: string;
  saveLabel: string;
  saving: string;
  savingDiscount: string;
  searchPlaceholder: string;
  subtitle: string;
  successCreated: string;
  successDiscountUpdated: string;
  successUpdated: string;
  tableActions: string;
  taxIdLabel: string;
  taxIdPlaceholder: string;
  title: string;
  totalBillsLabel: string;
  totalPurchaseLabel: string;
  updateTitle: string;
  shippingSectionTitle: string;
  shippingContactLabel: string;
  shippingPhoneLabel: string;
  shippingAddressLabel: string;
  shippingProvinceLabel: string;
  shippingSubDistrictLabel: string;
  shippingDistrictLabel: string;
  shippingPostalCodeLabel: string;
  deliveryNoteLabel: string;
  addShippingAddressBtn: string;
  noShippingAddresses: string;
  useCustomerAddressLabel: string;
  shippingLabelLabel: string;
  shippingLabelPlaceholder: string;
  recipientNameLabel: string;
  recipientPhoneLabel: string;
  defaultAddressLabel: string;
  setAsDefaultLabel: string;
  removeAddressBtn: string;
};

export type CustomerNetworkManagerCustomerNetworkManagerProps = {
  dictionary: CustomerNetworkManagerCustomerNetworkDictionary;
  locale: Locale;
};

export type CustomerNetworkManagerLocalShippingAddress = {
  _tempId: string;
  _isNew: boolean;
  _isDeleted: boolean;
  id?: string;
  label: string;
  recipient_name: string;
  recipient_phone: string;
  address: string;
  sub_district: string;
  district: string;
  province: string;
  postal_code: string;
  note: string;
  use_customer_address: boolean;
  is_default: boolean;
};

export type CustomerNetworkManagerCustomerFormState = {
  address: string;
  branch: string;
  email: string;
  full_name: string;
  is_active: boolean;
  level: string;
  note: string;
  phone: string;
  tax_id: string;
};
