export type StoreManagementPanelStoreManagementDictionary = {
  activeLabel: string;
  addStoreButton: string;
  addressLabel: string;
  basicInfoSection: string;
  contactSection: string;
  createStoreTitle: string;
  createSubmit: string;
  createSuccess: string;
  creating: string;
  currencyLabel: string;
  emptyStores: string;
  errorFallback: string;
  locationSection: string;
  logoLabel: string;
  logoPreviewLabel: string;
  logoSection: string;
  nameLabel: string;
  nameRequired: string;
  noLogoLabel: string;
  pageDescription: string;
  pageTitle: string;
  switchSectionTitle: string;
  paymentSection: string;
  phoneLabel: string;
  planLabel: string;
  plans: { growth: string; pro: string; starter: string };
  promptPayLabel: string;
  taxIdLabel: string;
  selectStoreLabel: string;
  storeListTitle: string;
  switchStoreAction: string;
  switchStoreHint: string;
  switchedSuccess: string;
  updateStoreTitle: string;
  updateSubmit: string;
  updateSuccess: string;
  updating: string;
  bankAccountsSection?: string;
  bankAccountsEmpty?: string;
  bankAccountAdd?: string;
  bankAccountBank?: string;
  bankAccountNo?: string;
  bankAccountName?: string;
  bankAccountAdded?: string;
  bankAccountDeleted?: string;
  bankAccountError?: string;
};

export type StoreManagementPanelProps = { dictionary: StoreManagementPanelStoreManagementDictionary };
